% this is a simplified version of 
% https://github.com/yihui/knitr/blob/master/inst/examples/knitr-beamer.Rnw
\documentclass{beamer}
\ifdefined\knitrout
  \renewenvironment{knitrout}{\begin{footnotesize}}{\end{footnotesize}}
\else
\fi
\usepackage{media9}
\begin{document}

\pgfdeclareimage[height=0.5cm]{university-logo}{images/CRUK_CAMBRIDGE_I_Pos_RGB_300}
\logo{\pgfuseimage{university-logo}}


\title{Introduction to Statistical analysis}
\author{Mark Dunning}
\date{12th March 2014}
\institute[Bioinformatics Core] % (optional, but mostly needed)
{

  Cancer Research Uk\\
  Cambridge Research Institute\\
  Robinson Way\\
  Cambridge \\
}

% very important to use option [fragile] for frames containing code output!

{
\usebackgroundtemplate{\includegraphics[width=\paperwidth]{images/criBackdrop.jpg}}
\begin{frame}
  \titlepage
\end{frame}
}

\begin{frame}{Outline}
  \tableofcontents
  % You might wish to add the option [pausesections]
\end{frame}

\section{Introduction}
\begin{frame}{The point of statistics}
\begin{itemize}
\item{Rarely feasible to study the whole population that we are interested in, so we take a sample instead}
\item{Assume that data collected represents a larger population}
\item{Use sample data to make conclusions about the overall population}
\end{itemize}
\includegraphics[height=5cm]{images/aSample.png}

\end{frame}

\begin{frame}{Data}
\begin{itemize}
\item{Type?}
\begin{itemize}
\item{Categorical (nominal) , e.g. Gender}
\item{Categorical with ordering (ordinal), e.g. Tumour grade }
\item{Discrete, e.g. Shoe size}
\item{Continuous, e.g. Body weight in kg}
\end{itemize}
\item{Independent  or dependent measurements}
\item{Representative of which population?}
\item{Distribution}
\begin{itemize}
\item{Normally distributed? Skewed? Bimodal?}
\end{itemize}
\end{itemize}
\end{frame}

\begin{frame}{Data type - example}
\begin{itemize}
\item{Sucess / failure of achieving a taks for a mouse which may be wild-type of knock-out, male or female, 2, 4 or 6 months old}
\end{itemize}
\includegraphics[height=5cm]{images/dataTypes1.png}
\end{frame}

\begin{frame}{Data type - example}
\begin{itemize}
\item{Gene expression in each cell sample which may be one of five cell-types (A,B,C,D,E)}
\end{itemize}
\includegraphics[height=5cm]{images/dataTypes2.png}
\end{frame}

\begin{frame}{Data type - example}
\begin{itemize}
\item{The number of bacteria for each subject which may be a cancer patient or a normal}
\end{itemize}
\includegraphics[height=5cm]{images/dataTypes3.png}
\end{frame}


\begin{frame}{Mesurements: Dependent / Independent?}
\begin{itemize}
\item{Measurements of gene expression taken from each of 20 individuals}
\item{Are any measurements more closely related than others?}
\begin{itemize}
\item{Siblings / littermates?}
\item{Same individual measured twice?}
\item{Batch effects?}
\end{itemize}
\item{If no reason - independent observations}
\end{itemize}
\end{frame}

\begin{frame}{Mesurements: Dependent / Independent?}
\begin{itemize}
\item{18 measurements; from repeating an experiment 6 times, each time in triplicate}
\end{itemize}
\includegraphics[height=5cm]{images/18measures.png}
\end{frame}

\begin{frame}{Mesurements: Dependent / Independent?}
\begin{itemize}
\item{Measuring blood pressure before and after treatment for 30 patients}
\end{itemize}
\includegraphics[height=5cm]{images/bloodPressure.png}
\end{frame}

\begin{frame}{Mesurements: Dependent / Independent?}
\begin{itemize}
\item{Measuring gene expression in each cell sample, which may be one of five cell-types from cancer patients of normal individuals}
\end{itemize}
\includegraphics[height=5cm]{images/complexData.png}
\end{frame}

\begin{frame}[fragile]{Continuous Data - Distribution}

<<echo=FALSE,fig.show='asis',fig.height=5,fig.width=10,warning=FALSE,message=FALSE>>=
library(ggplot2)
library(gridExtra)
x     = rnorm(10000, 0, 1)
p1 <- qplot(x,geom="histogram")   + xlim(-4,4) 
p2 <- qplot(x, geom="density")+ xlim(-4,4)
p3 <- qplot(1,x ,geom="boxplot")
grid.arrange(p1,p2,p3,ncol=3)
@

\end{frame}

\begin{frame}[fragile]{Continuous Data - Distribution}

<<echo=FALSE,fig.show='asis',fig.height=5,fig.width=10,warning=FALSE,message=FALSE>>=
library(RColorBrewer)
x     = rnorm(10000, 0, 1)
sd <- sd(x)
me <- mean(x)

dat <- data.frame(x=x)
rects <- data.frame(xstart = c(me-3*sd,me-2*sd,me-sd), xend = c(me+3*sd,me+2*sd,me+sd),col=letters[1:3])

normdist <- ggplot() +   geom_histogram(data = dat, aes(x))+  geom_rect(data = rects, aes(xmin = xstart, xmax = xend, ymin = -Inf, ymax = Inf,fill=col),alpha=0.4) + ylab("") + xlab("") + geom_segment(aes(x = me-sd, y = 999, xend = me +sd, yend=999),arrow=arrow(length=unit(0.5, "cm"), ends="both")) + geom_segment(aes(x = me-2*sd, y = 979, xend = me +2*sd, yend=979),arrow=arrow(length=unit(0.5, "cm"), ends="both"))  + 
geom_segment(aes(x = me-3*sd, y = 959, xend = me +3*sd, yend=959),arrow=arrow(length=unit(0.5, "cm"), ends="both")) + theme(legend.position="none")
            
normdist
@

\end{frame}

\begin{frame}[fragile]{Continuous Data - Distribution?}

<<echo=FALSE,fig.show='asis',fig.height=5,fig.width=10,warning=FALSE,message=FALSE>>=
library(reshape2)
x <- rnorm(200, 0, 2)
y <- rnorm(200, 0, 2)
dataset <- melt(data.frame(x,y))
p1 <- ggplot(dataset, aes(x= value)) + geom_histogram() + facet_wrap(~variable)

x <- rnorm(200, 0, 1)
y <- rnorm(200, 2, 2)
dataset <- melt(data.frame(x,y))
p2 <- ggplot(dataset, aes(x=variable,y= value)) + geom_boxplot()

x <- rnorm(2000, 950, 10)
x <- x[x>950]
dataset <- data.frame(x=x)
p3 <- ggplot(dataset,aes(x)) + geom_histogram()
skewdist <- p3
x <- rnorm(20, 950, 10)
dataset <- data.frame(x=x)

p4 <- ggplot(dataset,aes(x)) + geom_histogram()
grid.arrange(p1,p3,p2,p4,ncol=2)

@

\end{frame}

\begin{frame}[fragile]{Continuous Data - Descriptive Statistics}
<<echo=FALSE,fig.show='asis',fig.height=5,fig.width=12,warning=FALSE,message=FALSE>>=
normdist
@

\begin{itemize}
\item{Measures of location and spread}
\item{Mean and standard deviation}
\begin{itemize}

\item{$\bar{X} = \frac{X_1 + X_2 + \dots X_n}{n}$}
\item{$s.d = \sqrt{\frac{1}{N-1} \sum_{i=1}^N (x_i - \overline{x})^2}$}
\end{itemize}
\end{itemize}


\end{frame}

\begin{frame}[fragile]{Continuous Data - Descriptive Statistics}
<<echo=FALSE,fig.show='asis',fig.height=5,fig.width=12,warning=FALSE,message=FALSE>>=
skewdist
@
\begin{itemize}
\item{Median: middle value}
\item{Lower quartile: median bottom half of data}
\item{Upper quartile: median top half of data}
\end{itemize}
\end{frame}


\begin{frame}{Continuous Data - Descriptive Statistics Example}

E.g. No. of facebook friends for 7 colleagues\\
311, 345, 270, 310, 243, 5300, 11
\begin{itemize}
\item{Measures of location and spread}
\item{Mean and standard deviation}
\begin{itemize}

\item{$\bar{X} = \frac{X_1 + X_2 + \dots X_n}{n} = 970$}
\item{$s.d = \sqrt{\frac{1}{N-1} \sum_{i=1}^N (x_i - \overline{x})^2}=1912.57$}

\end{itemize}
\item{Median and interquartile range}
\begin{itemize}
\item{11, {\color{orange}243}, 270, {\color{red}310}, 311, {\color{orange}345},5300}
\end{itemize}
\end{itemize}
\pause
<<echo=FALSE,fig.show='asis',fig.height=5,fig.width=12,warning=FALSE,message=FALSE>>=
friends <- c(311, 345, 270, 310, 243, 5300, 11)
boxplot(friends,horizontal=T)
@

\end{frame}

\begin{frame}{Continuous Data - Descriptive Statistics Example}

E.g. No. of facebook friends for 7 colleagues\\
311, 345, 270, 310, 243, {\color{red}530}, 11


\begin{itemize}
\item{Measures of location and spread}
\item{Mean and standard deviation}
\begin{itemize}

\item{$\bar{X} = \frac{X_1 + X_2 + \dots X_n}{n} = 289$}
\item{$s.d = \sqrt{\frac{1}{N-1} \sum_{i=1}^N (x_i - \overline{x})^2}=153.79$}

\end{itemize}
\item{Median and interquartile range}
\begin{itemize}
\item{11, {\color{orange}243}, 270, {\color{red}310}, 311, {\color{orange}345},5300}
\end{itemize}
\end{itemize}
\pause
<<echo=FALSE,fig.show='asis',fig.height=5,fig.width=12,warning=FALSE,message=FALSE>>=
friends <- c(311, 345, 270, 310, 243, 530, 11)
boxplot(friends,horizontal=T)
@
\end{frame}

\begin{frame}{Categorical Data}

\begin{itemize}
\item{Summarised by counts and percentages}
\item{Examples}
\begin{itemize}
\item{19 / 82 (23$\%$) subjects had Grade IV tumour}
\item{48 / 82 (58$\%$) subjects had Diarrheoa as a Adverse Event}
\end{itemize}
\end{itemize}
\end{frame}


\begin{frame}{Standard Deviation and Standard Error}
\begin{itemize}
\item{Commonly confused}
\item{Standard deviation}
\begin{itemize}
\item{Measure of spread of data}
\item{Used for describing \textbf{\textit{population}}}
\end{itemize}
\item{Standard error}
\begin{itemize}
\item{Variability of the mean from repeated sampling}
\item{Precision of the mean}
\item{Used to calculate confidence interval}
\end{itemize}
\item{SD: How widely scattered measurements are}
\item{SE: Uncertainty in \textbf{\textit{estimate}} of sample mean}
\end{itemize}
\end{frame}


\begin{frame}{Confidence intervals for the mean}
\begin{itemize}
\item{Confidence Interval (CI) is a random interval}
\item{In repeated experiments}
\begin{itemize}
\item{95$\%$ of time cover the mean}
\end{itemize}
\item{Looser interpretation 95$\%$ of time}
95$\%$ CI: $(\bar{X} - 1.96 \times se, \bar{X} -+ 1.96 \times se)$\\
\end{itemize}
For facebook friends data:\\
$se = \frac{sd}{\sqrt(n)} = \frac{154}{\sqrt{7}} = 58 $

Mean 289, 95$\%$ CI ( $289 - (1.96 \times 58),  289 + (1.96 \times 58)$)\\
Mean 289, 95$\%$ CI ( 175,  402)

\end{frame}

\end{document}